
-- Outdated Version. Join .gg/seluwia
-- Outdated Version. Join .gg/seluwia
-- Outdated Version. Join .gg/seluwia
-- Outdated Version. Join .gg/seluwia
-- Outdated Version. Join .gg/seluwia
-- Outdated Version. Join .gg/seluwia
-- Outdated Version. Join .gg/seluwia
-- Outdated Version. Join .gg/seluwia
-- Outdated Version. Join .gg/seluwia
-- Outdated Version. Join .gg/seluwia
-- Outdated Version. Join .gg/seluwia
-- Outdated Version. Join .gg/seluwia
-- Outdated Version. Join .gg/seluwia



-- script made by Seluwia
-- offical server to get the script (recommend if you need support)
-- Outdated Version. Join .gg/seluwia
-- beep
-- beep

-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
game.Players.LocalPlayer:Kick("Outdated Version. Join .gg/seluwia")
