
-- Outdated Version. Join .gg/vyvs
-- Outdated Version. Join .gg/vyvs
-- Outdated Version. Join .gg/vyvs
-- Outdated Version. Join .gg/vyvs
-- Outdated Version. Join .gg/vyvs
-- Outdated Version. Join .gg/vyvs
-- Outdated Version. Join .gg/vyvs
-- Outdated Version. Join .gg/vyvs
-- Outdated Version. Join .gg/vyvs
-- Outdated Version. Join .gg/vyvs
-- Outdated Version. Join .gg/vyvs
-- Outdated Version. Join .gg/vyvs
-- Outdated Version. Join .gg/vyvs



-- script made by Seluwia
-- offical server to get the script (recommend if you need support)
-- Outdated Version. Join .gg/vyvs
-- beep
-- beep

-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
-- beep
game.Players.LocalPlayer:Kick("Outdated Version. Join .gg/vyvs")
